### ISSUE TITLE
Grid View with ability to export its content to csv 

### ISSUE THREAD

**Issue by yudilee** [schmunk42/yii2-extension-requests#5]
I need GridView widget with ability ti export it's content into csv. Grid view in yii 2 is really awesome especially it's ability to search and view it result in grid. i really want grid view to have ability to export it to csv directly to browser. Thanks in Advance

**Comment by cebe** [comment]
This is more like another wrapper around dataprovider than related to gridview.

**Comment by yudilee** [comment]
Do you have any ideas how to do that, thanks for helping

**Comment by samdark** [comment]
It already exists: http://demos.krajee.com/grid-demo

**Comment by yudilee** [comment]
I already use it. But i cant find how to generate csv from that widget. Sorry if i'm wrong.

**Comment by samdark** [comment]
Ah, right.

**Comment by kartik-v** [comment]
The `\kartik\grid\GridView` extension is now updated to include the export feature for HTML and CSV formats (and EXCEL is in process) via a newly developed JQuery plugin. It allows you to export the <b>grid data displayed on screen</b>. You can refer the [demo](http://demos.krajee.com/grid-demo) and [documentation](http://demos.krajee.com/grid#grid-export) for the new features. The export plugin has some intelligence to detect the HTML5 download attribute for the supported modern browsers.
Check the Export Data Button in the demo. The EXCEL export is being worked upon.

**Comment by schmunk42** [comment]
Very nice. Please let me know when we can close the ticket.

Von meinem iPhone gesendet

**Comment by yudilee** [comment]
Amazing. Thanks a lot.

**Comment by kartik-v** [comment]
FYI... the `yii2-grid` extension has been enhanced:
1. to work with all browsers in a more secure and reliable manner
2. to support export of the displayed grid and download as HTML, TEXT, CSV, and EXCEL formats
3. configurable file names for export
4. configurable worksheet name for excel
5. configurable column and row delimiters for export as TEXT or CSV
6. i18n/translation enabled
7. and the extension is a [module now](http://demos.krajee.com/grid#module) which has potential to add on more features later.

and more other features... Refer the updated [documentation](http://demos.krajee.com/grid#grid-export) and [demo](http://demos.krajee.com/grid-demo).

**Comment by yudilee** [comment]
Thanks for this feature. So amazing.
