### ISSUE TITLE
Adjacency List behavior

### ISSUE THREAD

**Issue by schmunk42** [schmunk42/yii2-extension-requests#7]
This extension allows you to get functional for parent-child trees.

Reference from Yii 2 as nested set: https://github.com/creocoder/yii2-nested-set-behavior
Would be nice if we could have the same API.

A rather pre-alpha implementation from Yii 1: https://github.com/schmunk42/yii-adjacency-list-behavior.

**Comment by vambus** [comment]
I believe this: https://github.com/vanik/yii2-adjacency-list-behavior might answer our needs. However I believe that we should actually mimic @creocoder https://github.com/creocoder/yii2-nested-set-behavior , while applying adjacency list logic to it to benefit from unification and clever method set creocoder provided.

**Comment by schmunk42** [comment]
Thanks for the info, I'll close this.
