### ISSUE TITLE
Auth/Rights/RBAC module

### ISSUE THREAD

**Issue by schmunk42** [schmunk42/yii2-extension-requests#8]
RBAC Web UI, there are [several implementations for Yii 1](http://www.yiiframework.com/extensions/?category=1&sort=rating.desc).

Management of auth-items and assignments.
- should be able to handle thousands of users (grid, paging, ...)
- should be able to handle hundreds of auth-items
- display inheritance
- biz-rule AND data editing for admins
- superuser role?
- llinkage to user module https://github.com/phundament/yii2-extension-requests/issues/4

Some for Yii 2:
https://github.com/robregonm/yii2-auth
https://github.com/mdmsoft/yii2-admin

@robregonm How's the status of your RBAC part, sorry didn't have a look yet.

**Comment by samdark** [comment]
We want web UI for RBAC as core extension.

**Comment by schmunk42** [comment]
Nice, so we can close this.

btw: What's about a user management extension?
Please have a look at https://github.com/communityii/yii2-user/issues/1#issuecomment-39002240 - do you have another idea for a rather loose connection between user management and RBAC.

**Comment by samdark** [comment]
Not sure about full-featured yii-user extension yet.
